codebender_library_status_check:
    pattern:  /status
    defaults: { _controller: CodebenderLibraryBundle:Default:status }

codebender_unit_test:
    pattern:  /{auth_key}/test
    defaults: { _controller: CodebenderLibraryBundle:Test:test }

codebender_api_handler:
    pattern:  /{auth_key}/{version}
    defaults: { _controller: CodebenderLibraryBundle:Default:apiHandler }
    methods:  [POST]

codebender_library_check_github_updates:
    pattern: /{auth_key}/{version}/checkGithubUpdates
    defaults: {_controller:CodebenderLibraryBundle:Default:checkGithubUpdates}

codebender_library_download:
    pattern: /{auth_key}/{version}/download
    defaults: { _controller: CodebenderLibraryBundle:Default:download }

codebender_library_view_library:
    pattern:  /{auth_key}/{version}/view
    defaults: { _controller: CodebenderLibraryBundle:Default:getLibraryCode, renderView: true }

codebender_library_new_external:
    pattern: /{auth_key}/{version}/new
    defaults: {_controller:CodebenderLibraryBundle:Default:newLibrary}
    methods:  [GET, POST]

#codebender_library_compile_examples:
#    pattern:  /{auth_key}/{version}/compile
#    defaults: { _controller: CodebenderLibraryBundle:Default:compileLibraryExamples }

codebender_library_get_library_git_meta:
    pattern: /getlibgitmeta
    defaults: {_controller:CodebenderLibraryBundle:Default:getLibraryGitMeta}
    methods:  [POST]

codebender_library_search:
    pattern: /search
    defaults: {_controller:CodebenderLibraryBundle:Default:search}

codebender_library_status_change:
    pattern: /statuschange
    defaults: {_controller:CodebenderLibraryBundle:Default:changeLibraryStatus}
    methods:  [POST]

codebender_library_get_keywords:
    pattern:  /{auth_key}/{version}/getKeywords
    defaults: { _controller: CodebenderLibraryBundle:Default:getKeywords}

