codebender_library_status_check:
    pattern:  /status
    defaults: { _controller: CodebenderLibraryBundle:Default:status }

codebender_unit_test:
    pattern:  /{auth_key}/test
    defaults: { _controller: CodebenderLibraryBundle:Test:test }

codebender_api_handler:
    pattern:  /{auth_key}/{version}
    defaults: { _controller: CodebenderLibraryBundle:Default:apiHandler }
    methods:  [POST]

codebender_library_view_library:
    pattern:  /{auth_key}/view
    defaults: { _controller: CodebenderLibraryBundle:Views:viewLibrary }

#codebender_library_compile_examples:
#    pattern:  /{auth_key}/{version}/compile
#    defaults: { _controller: CodebenderLibraryBundle:Default:compileLibraryExamples }

codebender_library_get_library_git_meta:
    pattern: /{auth_key}/getlibgitmeta
    defaults: {_controller:CodebenderLibraryBundle:Default:getLibraryGitMeta}
    methods:  [POST]

codebender_library_download:
    pattern: /{auth_key}/download/{library}
    defaults: { _controller: CodebenderLibraryBundle:Views:download }

codebender_library_new_external:
    pattern: /{auth_key}/new
    defaults: {_controller:CodebenderLibraryBundle:Views:newLibrary}
    methods:  [GET, POST]

codebender_library_check_github_updates:
    pattern: /{auth_key}/gitUpdates
    defaults: {_controller:CodebenderLibraryBundle:Views:gitUpdates}

codebender_library_search:
    pattern: /{auth_key}/search
    defaults: { _controller: CodebenderLibraryBundle:Views:search }

codebender_library_status_change:
    pattern: /{auth_key}/toggleStatus/{library}
    defaults: {_controller:CodebenderLibraryBundle:Views:changeLibraryStatus}
    methods:  [POST]

codebender_library_get_keywords:
    pattern:  /{auth_key}/{version}/getKeywords
    defaults: { _controller: CodebenderLibraryBundle:Default:getKeywords}

