codebender_library_status_check:
    pattern:  /status
    defaults: { _controller: CodebenderLibraryBundle:Default:status }

codebender_compiler_test:
    pattern:  /{auth_key}/test/
    defaults: { _controller: CodebenderLibraryBundle:Default:test }

codebender_library_list:
    pattern:  /{auth_key}/{version}
    defaults: { _controller: CodebenderLibraryBundle:Default:list }

codebender_library_get_example_code:
    pattern:  /{auth_key}/{version}/get
    defaults: { _controller: CodebenderLibraryBundle:Default:getExampleCode }

codebender_library_fetch_library_code:
    pattern:  /{auth_key}/{version}/fetch
    defaults: { _controller: CodebenderLibraryBundle:Default:getLibraryCode }

codebender_library_new_external:
    pattern: /{auth_key}/{version}/new
    defaults: {_controller:CodebenderLibraryBundle:Default:newLibrary}

codebender_library_verify_built_in_examples:
    pattern: /{auth_key}/{version}/verifybuiltin
    defaults: {_controller:CodebenderLibraryBundle:Default:verifyBuiltInExamples}

codebender_library_verify_external_examples:
    pattern: /{auth_key}/{version}/verifyexternal/{library}
    defaults: {_controller:CodebenderLibraryBundle:Default:verifyExternalExamples, library: null}
