parameters:
#    codebender_library.example.class: Codebender\LibraryBundle\Example

services:
#    codebender_library.example:
#        class: %codebender_library.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
