parameters:
#    codebender_library.example.class: Codebender\LibraryBundle\Example
    codebender_library.handler.class: Codebender\LibraryBundle\Handler\DefaultHandler

services:
#    codebender_library.example:
#        class: %codebender_library.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    codebender_library.handler:
        class:  %codebender_library.handler.class%
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            containerInterface: "@service_container"